Repository groue/GRDB.swift, pull requests merged in 2020-03, with the labels that each got.

#710 Check if all migrations have been applied
  CHANGELOG.md
  Documentation/AppGroupContainers.md
  GRDB/Migration/DatabaseMigrator.swift
  README.md
  Tests/GRDBTests/DatabaseMigratorTests.swift
Labels: enhancement

#713 Enhance DatabaseMigrator isolation
  CHANGELOG.md
  GRDB/Core/Database.swift
  GRDB/Core/DatabasePool.swift
  GRDB/Core/DatabaseQueue.swift
  GRDB/Core/DatabaseReader.swift
  GRDB/Core/DatabaseWriter.swift
  GRDB/Migration/DatabaseMigrator.swift
  Tests/GRDBTests/DatabasePoolBackupTests.swift
Labels: enhancement

#720 Turn deprecated APIs into unavailable ones
  CHANGELOG.md
  GRDB.xcodeproj/project.pbxproj
  GRDB/Core/Configuration.swift
  GRDB/Core/Database.swift
  GRDB/Core/DatabaseError.swift
  GRDB/Core/DatabasePool.swift
  GRDB/Core/DatabaseQueue.swift
  GRDB/Core/DatabaseReader.swift
  GRDB/Core/FetchRequest.swift
  GRDB/Core/SQLLiteral.swift
  GRDB/Core/Statement.swift
  GRDB/FTS/FTS3Pattern.swift
  GRDB/FTS/FTS3TokenizerDescriptor.swift
  GRDB/FTS/FTS4.swift
  GRDB/Fixit/GRDB-4.0.swift
  GRDB/Fixit/GRDB-5.0.swift
  GRDB/Migration/DatabaseMigrator.swift
  GRDB/QueryInterface/Request/Association/AssociationAggregate.swift
  GRDB/QueryInterface/SQL/SQLExpression+QueryInterface.swift
  GRDB/QueryInterface/SQL/SQLSpecificExpressible+QueryInterface.swift
  GRDB/QueryInterface/Schema/TableDefinition.swift
  GRDB/ValueObservation/ValueObservation+Count.swift
  GRDB/ValueObservation/ValueObservation+DatabaseValueConvertible.swift
  GRDB/ValueObservation/ValueObservation+FetchableRecord.swift
  GRDB/ValueObservation/ValueObservation+Row.swift
  GRDB/ValueObservation/ValueReducer/CompactMap.swift
  GRDB/ValueObservation/ValueReducer/Fetch.swift
  GRDB/ValueObservation/ValueReducer/Map.swift
  GRDB/ValueObservation/ValueReducer/RemoveDuplicates.swift
  GRDBCustom.xcodeproj/project.pbxproj
  README.md
  Tests/GRDBTests/AssociationBelongsToRowScopeTests.swift
  Tests/GRDBTests/AssociationHasOneThroughRowScopeTests.swift
  Tests/GRDBTests/CompilationProtocolTests.swift
  Tests/GRDBTests/DatabaseConfigurationTests.swift
  Tests/GRDBTests/DatabaseErrorTests.swift
  Tests/GRDBTests/DatabaseMigratorTests.swift
  Tests/GRDBTests/DatabasePoolBackupTests.swift
  Tests/GRDBTests/DatabasePoolConcurrencyTests.swift
  Tests/GRDBTests/DatabaseTests.swift
  Tests/GRDBTests/EncryptionTests.swift
  Tests/GRDBTests/FTS3PatternTests.swift
  Tests/GRDBTests/FTS3TableBuilderTests.swift
  Tests/GRDBTests/FTS3TokenizerTests.swift
  Tests/GRDBTests/FTS4TableBuilderTests.swift
  Tests/GRDBTests/FetchRequestTests.swift
  Tests/GRDBTests/PoolTests.swift
  Tests/GRDBTests/QueryInterfaceExtensibilityTests.swift
  Tests/GRDBTests/QueryInterfaceRequestTests.swift
  Tests/GRDBTests/SQLLiteralTests.swift
  Tests/GRDBTests/SQLRequestTests.swift
  Tests/GRDBTests/TableDefinitionTests.swift
  Tests/GRDBTests/ValueObservationCountTests.swift
  Tests/GRDBTests/ValueObservationDatabaseValueConvertibleTests.swift
  Tests/GRDBTests/ValueObservationFetchTests.swift
  Tests/GRDBTests/ValueObservationQueryInterfaceRequestTests.swift
  Tests/GRDBTests/ValueObservationRecordTests.swift
  Tests/GRDBTests/ValueObservationRowTests.swift
  Tests/GRDBTests/ValueObservationSchedulingTests.swift
  Tests/GRDBTests/VirtualTableModuleTests.swift
Labels: enhancement

#721 SE-0249: Key Path Expressions as Functions
  CHANGELOG.md
  GRDB/Core/Database+Schema.swift
  GRDB/Core/SQLLiteral.swift
  GRDB/Core/Statement.swift
  GRDB/Core/TransactionObserver.swift
  GRDB/FTS/FTS4.swift
  GRDB/FTS/FTS5.swift
  GRDB/FTS/FTS5Pattern.swift
  GRDB/Migration/DatabaseMigrator.swift
  GRDB/QueryInterface/Request/QueryInterfaceRequest.swift
  GRDB/QueryInterface/SQL/SQLAssociation.swift
  GRDB/QueryInterface/SQL/SQLCollection.swift
  GRDB/QueryInterface/SQL/SQLExpression+QueryInterface.swift
  GRDB/QueryInterface/SQL/SQLFunctions.swift
  GRDB/QueryInterface/SQL/SQLQuery.swift
  GRDB/QueryInterface/SQL/SQLRelation.swift
  GRDB/QueryInterface/SQLGeneration/SQLGenerationContext.swift
  GRDB/QueryInterface/SQLGeneration/SQLQueryGenerator.swift
  GRDB/QueryInterface/SQLInterpolation+QueryInterface.swift
  GRDB/QueryInterface/Schema/TableDefinition.swift
  GRDB/QueryInterface/TableRecord+Association.swift
  GRDB/Record/FetchedRecordsController.swift
  GRDB/Record/PersistableRecord.swift
  GRDB/Utils/Pool.swift
  Tests/GRDBTests/DatabaseRegionTests.swift
  Tests/GRDBTests/DatabaseValueConvertibleFetchTests.swift
  Tests/GRDBTests/DerivableRequestTests.swift
  Tests/GRDBTests/FetchableRecord+QueryInterfaceRequestTests.swift
  Tests/GRDBTests/FetchableRecordTests.swift
  Tests/GRDBTests/FetchedRecordsControllerTests.swift
  Tests/GRDBTests/Record+QueryInterfaceRequestTests.swift
  Tests/GRDBTests/RecordMinimalPrimaryKeyRowIDTests.swift
  Tests/GRDBTests/RecordPrimaryKeyHiddenRowIDTests.swift
  Tests/GRDBTests/RecordPrimaryKeyMultipleTests.swift
  Tests/GRDBTests/RecordPrimaryKeyRowIDTests.swift
  Tests/GRDBTests/RecordPrimaryKeySingleWithReplaceConflictResolutionTests.swift
  Tests/GRDBTests/SelectStatementTests.swift
  Tests/GRDBTests/StatementColumnConvertibleFetchTests.swift
  Tests/GRDBTests/TableDefinitionTests.swift
  Tests/GRDBTests/ValueObservationDatabaseValueConvertibleTests.swift
  Tests/GRDBTests/ValueObservationRecordTests.swift
Labels: enhancement

#722 SE-0253: Callable values of user-defined nominal types
  CHANGELOG.md
  GRDB/Fixit/GRDB-5.0.swift
  GRDB/QueryInterface/SQL/SQLFunctions.swift
  README.md
  Tests/GRDBTests/QueryInterfaceExpressionsTests.swift
Labels: enhancement

#724 SE-0242: Synthesize default values for the memberwise initializer
  CHANGELOG.md
  GRDB/Core/StatementAuthorizer.swift
  GRDB/Core/Support/StandardLibrary/DatabaseValueConvertible+Decodable.swift
  GRDB/Core/Support/StandardLibrary/DatabaseValueConvertible+Encodable.swift
  GRDB/Migration/Migration.swift
  GRDB/QueryInterface/Request/Association/AssociationAggregate.swift
  GRDB/QueryInterface/Request/QueryInterfaceRequest.swift
  GRDB/QueryInterface/SQL/SQLQuery.swift
  GRDB/QueryInterface/SQL/SQLRelation.swift
  GRDB/Record/EncodableRecord+Encodable.swift
Labels: enhancement

#728 Make ValueObservation error handling mandatory
  CHANGELOG.md
  GRDB/Fixit/GRDB-5.0.swift
  GRDB/ValueObservation/ValueObservation.swift
  README.md
  Tests/GRDBTests/ValueObservationCombineTests.swift
  Tests/GRDBTests/ValueObservationCompactMapTests.swift
  Tests/GRDBTests/ValueObservationCountTests.swift
  Tests/GRDBTests/ValueObservationDatabaseValueConvertibleTests.swift
  Tests/GRDBTests/ValueObservationExtentTests.swift
  Tests/GRDBTests/ValueObservationFetchTests.swift
  Tests/GRDBTests/ValueObservationMapTests.swift
  Tests/GRDBTests/ValueObservationQueryInterfaceRequestTests.swift
  Tests/GRDBTests/ValueObservationReadonlyTests.swift
  Tests/GRDBTests/ValueObservationRecordTests.swift
  Tests/GRDBTests/ValueObservationReducerTests.swift
  Tests/GRDBTests/ValueObservationRegionRecordingTests.swift
  Tests/GRDBTests/ValueObservationRowTests.swift
  Tests/GRDBTests/ValueObservationSchedulingTests.swift
Labels: enhancement

#729 ValueObservation always emits an initial value
  CHANGELOG.md
  GRDB/Core/DatabaseSnapshot.swift
  GRDB/Core/DatabaseWriter.swift
  GRDB/Fixit/GRDB-5.0.swift
  GRDB/ValueObservation/ValueObservation.swift
  GRDB/ValueObservation/ValueObserver.swift
  README.md
  Tests/GRDBTests/ValueObservationCompactMapTests.swift
  Tests/GRDBTests/ValueObservationMapTests.swift
  Tests/GRDBTests/ValueObservationReducerTests.swift
  Tests/GRDBTests/ValueObservationRegionRecordingTests.swift
  Tests/GRDBTests/ValueObservationSchedulingTests.swift
Labels: enhancement

#730 fix typo
  README.md
Labels: documentation bug

#731 Hide ValueObservation implementation details
  CHANGELOG.md
  GRDB/Core/DatabaseReader.swift
  GRDB/Core/DatabaseSnapshot.swift
  GRDB/Core/DatabaseWriter.swift
  GRDB/Fixit/GRDB-5.0.swift
  GRDB/ValueObservation/ValueObservation+DatabaseValueConvertible.swift
  GRDB/ValueObservation/ValueObservation+FetchableRecord.swift
  GRDB/ValueObservation/ValueObservation+MapReducer.swift
  GRDB/ValueObservation/ValueObservation+Row.swift
  GRDB/ValueObservation/ValueObservation.swift
  GRDB/ValueObservation/ValueObserver.swift
  GRDB/ValueObservation/ValueReducer/Combine.swift
  GRDB/ValueObservation/ValueReducer/CompactMap.swift
  GRDB/ValueObservation/ValueReducer/Fetch.swift
  GRDB/ValueObservation/ValueReducer/Map.swift
  GRDB/ValueObservation/ValueReducer/RemoveDuplicates.swift
  GRDB/ValueObservation/ValueReducer/ValueReducer.swift
  README.md
  Tests/GRDBTests/GRDBTestCase.swift
  Tests/GRDBTests/ValueObservationCompactMapTests.swift
  Tests/GRDBTests/ValueObservationExtentTests.swift
  Tests/GRDBTests/ValueObservationMapTests.swift
  Tests/GRDBTests/ValueObservationReducerTests.swift
  Tests/GRDBTests/ValueObservationSchedulingTests.swift
Labels: enhancement

#732 Remove ValueObservation.compactMap
  CHANGELOG.md
  GRDB.xcodeproj/project.pbxproj
  GRDB/Core/DatabaseSnapshot.swift
  GRDB/Core/DatabaseWriter.swift
  GRDB/Fixit/GRDB-5.0.swift
  GRDB/ValueObservation/ValueObservation.swift
  GRDB/ValueObservation/ValueObserver.swift
  GRDB/ValueObservation/ValueReducer/CompactMap.swift
  GRDB/ValueObservation/ValueReducer/ValueReducer.swift
  GRDBCustom.xcodeproj/project.pbxproj
  README.md
  Tests/CocoaPods/SQLCipher3/GRDBTests.xcodeproj/project.pbxproj
  Tests/CocoaPods/SQLCipher4/GRDBTests.xcodeproj/project.pbxproj
  Tests/GRDBTests/ValueObservationCompactMapTests.swift
Labels: enhancement

#736 Relax ValueObservation Guarantees
  CHANGELOG.md
  GRDB.xcodeproj/project.pbxproj
  GRDB/Core/DatabasePool.swift
  GRDB/Core/DatabaseQueue.swift
  GRDB/Core/DatabaseReader.swift
  GRDB/Core/DatabaseSnapshot.swift
  GRDB/Core/DatabaseValueConvertible.swift
  GRDB/Core/DatabaseWriter.swift
  GRDB/Core/StatementColumnConvertible.swift
  GRDB/Fixit/GRDB-5.0.swift
  GRDB/Utils/Utils.swift
  GRDB/ValueObservation/ValueObservation+DatabaseValueConvertible.swift
  GRDB/ValueObservation/ValueObservation.swift
  GRDB/ValueObservation/ValueObserver.swift
  GRDB/ValueObservation/ValueReducer/ValueReducer.swift
  GRDBCustom.xcodeproj/project.pbxproj
  README.md
  Tests/CocoaPods/SQLCipher3/GRDBTests.xcodeproj/project.pbxproj
  Tests/CocoaPods/SQLCipher4/GRDBTests.xcodeproj/project.pbxproj
  Tests/GRDBTests/AssociationPrefetchingCodableRecordTests.swift
  Tests/GRDBTests/AssociationPrefetchingFetchableRecordTests.swift
  Tests/GRDBTests/DatabasePoolConcurrencyTests.swift
  Tests/GRDBTests/DatabaseReaderTests.swift
  Tests/GRDBTests/FailableTestCase.swift
  Tests/GRDBTests/ValueObservationCombineTests.swift
  Tests/GRDBTests/ValueObservationCountTests.swift
  Tests/GRDBTests/ValueObservationDatabaseValueConvertibleTests.swift
  Tests/GRDBTests/ValueObservationFetchTests.swift
  Tests/GRDBTests/ValueObservationMapTests.swift
  Tests/GRDBTests/ValueObservationQueryInterfaceRequestTests.swift
  Tests/GRDBTests/ValueObservationReadonlyTests.swift
  Tests/GRDBTests/ValueObservationRecordTests.swift
  Tests/GRDBTests/ValueObservationRecorder.swift
  Tests/GRDBTests/ValueObservationRecorderTests.swift
  Tests/GRDBTests/ValueObservationReducerTests.swift
  Tests/GRDBTests/ValueObservationRowTests.swift
  Tests/GRDBTests/ValueObservationSchedulingTests.swift
Labels: enhancement

#737 Force implicit database region for ValueObservation
  CHANGELOG.md
  GRDB/Core/Database+Statements.swift
  GRDB/Core/Database.swift
  GRDB/Core/DatabaseRegion.swift
  GRDB/Core/DatabaseWriter.swift
  GRDB/Core/FetchRequest.swift
  GRDB/Core/Statement.swift
  GRDB/Core/StatementAuthorizer.swift
  GRDB/Fixit/GRDB-5.0.swift
  GRDB/QueryInterface/Request/QueryInterfaceRequest.swift
  GRDB/QueryInterface/SQLGeneration/SQLQueryGenerator.swift
  GRDB/ValueObservation/ValueObservation+Count.swift
  GRDB/ValueObservation/ValueObservation+DatabaseValueConvertible.swift
  GRDB/ValueObservation/ValueObservation+FetchableRecord.swift
  GRDB/ValueObservation/ValueObservation+MapReducer.swift
  GRDB/ValueObservation/ValueObservation+Row.swift
  GRDB/ValueObservation/ValueObservation.swift
  GRDB/ValueObservation/ValueObserver.swift
  GRDB/ValueObservation/ValueReducer/Combine.swift
  GRDB/ValueObservation/ValueReducer/Fetch.swift
  GRDB/ValueObservation/ValueReducer/Map.swift
  GRDB/ValueObservation/ValueReducer/RemoveDuplicates.swift
  GRDB/ValueObservation/ValueReducer/ValueReducer.swift
  README.md
  TODO.md
  Tests/GRDBTests/GRDBTestCase.swift
  Tests/GRDBTests/ValueObservationCombineTests.swift
  Tests/GRDBTests/ValueObservationDatabaseValueConvertibleTests.swift
  Tests/GRDBTests/ValueObservationExtentTests.swift
  Tests/GRDBTests/ValueObservationFetchTests.swift
  Tests/GRDBTests/ValueObservationMapTests.swift
  Tests/GRDBTests/ValueObservationReadonlyTests.swift
  Tests/GRDBTests/ValueObservationRecorder.swift
  Tests/GRDBTests/ValueObservationReducerTests.swift
  Tests/GRDBTests/ValueObservationRegionRecordingTests.swift
  Tests/GRDBTests/ValueObservationSchedulingTests.swift
Labels: enhancement

#738 Remove all observationForCount/All/First methods
  CHANGELOG.md
  GRDB.xcodeproj/project.pbxproj
  GRDB/Core/DatabaseValueConvertible.swift
  GRDB/Core/StatementColumnConvertible.swift
  GRDB/Fixit/GRDB-5.0.swift
  GRDB/ValueObservation/ValueObservation+Count.swift
  GRDB/ValueObservation/ValueObservation+DatabaseValueConvertible.swift
  GRDB/ValueObservation/ValueObservation+FetchableRecord.swift
  GRDB/ValueObservation/ValueObservation+Row.swift
  GRDB/ValueObservation/ValueObservation.swift
  GRDBCustom.xcodeproj/project.pbxproj
  README.md
  Tests/GRDBTests/ValueObservationCombineTests.swift
  Tests/GRDBTests/ValueObservationCountTests.swift
  Tests/GRDBTests/ValueObservationDatabaseValueConvertibleTests.swift
  Tests/GRDBTests/ValueObservationQueryInterfaceRequestTests.swift
  Tests/GRDBTests/ValueObservationRecordTests.swift
  Tests/GRDBTests/ValueObservationRowTests.swift
Labels: enhancement

#742 ValueObservation scheduling is no longer an attribute of the observation
  CHANGELOG.md
  GRDB.xcodeproj/project.pbxproj
  GRDB/Core/DatabasePool.swift
  GRDB/Core/DatabaseQueue.swift
  GRDB/Core/DatabaseReader.swift
  GRDB/Core/DatabaseSnapshot.swift
  GRDB/Core/DatabaseWriter.swift
  GRDB/Core/SerializedDatabase.swift
  GRDB/Fixit/GRDB-5.0.swift
  GRDB/ValueObservation/ValueObservation+MapReducer.swift
  GRDB/ValueObservation/ValueObservation.swift
  GRDB/ValueObservation/ValueObservationScheduler.swift
  GRDB/ValueObservation/ValueObserver.swift
  GRDBCustom.xcodeproj/project.pbxproj
  README.md
  Tests/CocoaPods/SQLCipher3/GRDBTests.xcodeproj/project.pbxproj
  Tests/CocoaPods/SQLCipher4/GRDBTests.xcodeproj/project.pbxproj
  Tests/GRDBTests/ValueObservationCombineTests.swift
  Tests/GRDBTests/ValueObservationDatabaseValueConvertibleTests.swift
  Tests/GRDBTests/ValueObservationExtentTests.swift
  Tests/GRDBTests/ValueObservationMapTests.swift
  Tests/GRDBTests/ValueObservationQueryInterfaceRequestTests.swift
  Tests/GRDBTests/ValueObservationRecordTests.swift
  Tests/GRDBTests/ValueObservationRecorder.swift
  Tests/GRDBTests/ValueObservationRecorderTests.swift
  Tests/GRDBTests/ValueObservationReducerTests.swift
  Tests/GRDBTests/ValueObservationRegionRecordingTests.swift
  Tests/GRDBTests/ValueObservationSchedulingTests.swift
  Tests/GRDBTests/ValueObservationTests.swift
Labels: enhancement

#744 Fix DatabaseMigrator deadlock with serial target queues
  GRDB/Migration/DatabaseMigrator.swift
  Tests/GRDBTests/DatabaseMigratorTests.swift
Labels: bug

#745 Explicit ValueObservation cancellation
  CHANGELOG.md
  Documentation/DemoApps/GRDBDemoiOS/GRDBDemoiOS/PlayersViewController.swift
  Documentation/WhyAdoptGRDB.md
  GRDB.xcodeproj/project.pbxproj
  GRDB/Core/DatabasePool.swift
  GRDB/Core/DatabaseQueue.swift
  GRDB/Core/DatabaseReader.swift
  GRDB/Core/DatabaseSnapshot.swift
  GRDB/Core/DatabaseWriter.swift
  GRDB/ValueObservation/DatabaseCancellable.swift
  GRDB/ValueObservation/ValueObservation.swift
  GRDB/ValueObservation/ValueObservationScheduler.swift
  GRDB/ValueObservation/ValueObserver.swift
  GRDBCustom.xcodeproj/project.pbxproj
  README.md
  Tests/GRDBTests/ValueObservationRecorder.swift
  Tests/GRDBTests/ValueObservationRegionRecordingTests.swift
  Tests/GRDBTests/ValueObservationTests.swift
Labels: enhancement
